server:
  port: 8186
  servlet:
    context-path: /customs-notification

spring:
  redis:
    port: 6379
    host: localhost
  rabbitmq:
    port: 5672
    host: localhost
    username: guest
    password: guest
