version: "3.2"
services:
    redis:
        image: 'bitnami/redis:latest'
        environment:
            - ALLOW_EMPTY_PASSWORD=yes
        ports:
            - "6379:6379"

    postgres_customs:
        image: postgres:10
        container_name: postgres_customs
        ports:
            - "5433:5432"
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=customs
        volumes:
            - ./postgresql:/var/lib/postgresql
        healthcheck:
          test: [ "CMD", "pg_isready", "-q", "-U", "postgres" ]
          interval: 5s
          timeout: 1s
          retries: 2
                
    liquibase_pg_customs:
        container_name: pg_updater
        image: liquibase/liquibase:4.15.0
        volumes:
            - ./docker/liquibase:/liquibase/changelog
        command: liquibase --url="jdbc:postgresql://postgres_customs:5432/customs" --changeLogFile=./changelog/changelog_customs.sql --username=postgres --password=postgres --log-level=INFO update
        depends_on:
            postgres_customs:
                condition: service_healthy