server:
  port: 8800
  servlet:
    context-path: /customs-core

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/customs
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: false
  liquibase:
    enabled: false